openapi: 3.0.0
servers:
  - description: Defines a Concept Set Expression
    url: https://github.com/OHDSI/Specifications/ConceptSetExpression/0.9.0
info:
  description: Concept Set definition based on OHDSI WebAPI definition(https://github.com/OHDSI/WebAPI/tree/master/src/main/java/org/ohdsi/webapi/conceptset) and Concept Set Expression based on OHDSI circe-be definition (https://github.com/OHDSI/circe-be/blob/master/src/main/java/org/ohdsi/circe/vocabulary/ConceptSetExpression.java)
  version: "0.9.0"
  title: Concept Set Expression
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /:
    get:
      summary: Get all concept sets
      operationId: getConceptSets
      description: |
        Used to retrieve all concept sets
      responses:
        '200':
          description: returns all concept sets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConceptSet'
        '400':
          description: bad input parameter
components:
  schemas:
    ConceptSet:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        conceptSetExpression:
          $ref: '#/components/schemas/ConceptSetExpression'
      type: object    
    ConceptSetExpression:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ConceptSetItem"
    ConceptSetItem:
      required:
        - concept
      properties:
        concept:
          $ref: '#/components/schemas/Concept'
        isExcluded:
          type: boolean
          description: Exclude the selected concept
        includeDescendants:
          type: boolean
          description: Include concepts that are descendants of the selected concept
        includeMapped:
          type: boolean
          description: Include concepts that are mapped to the seleected concept
      type: object
    Concept:
      type: object
      properties:
        conceptId:
          type: number
          description: Concept Id
          format: long
        conceptName:
          type: string
          description: Concept Name
        standardConcept:
          type: string
          description: |
            Type of standard concept. 'N' is 'Non Standard', 'S' is 'Standard', 'C' is 'Classification', 'U' is 'Unknown'
          enum:
            - "N"
            - "S"
            - "C"
            - "U"
        invalidReason:
          type: string
          description: |
            The invalid reason. 'V' is 'Valid', 'D' is 'Invalid', 'U' is 'Invalid'
          enum:
            - 'V'
            - 'D'
            - 'U'
        conceptCode:
          type: string
          description: The concept code
        domainId: 
          type: string
          description: The domain ID
          example: 'CONDITION'
        vocabularyId:
          type: string
          description: The vocabulary Id
          example: 'SNOMED'
        conceptClassId:
          type: string
          description: The concept class
          example: 'Clinical Finding'